# Generated by Django 4.0.5 on 2022-06-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sketchpad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание')),
                ('status', models.CharField(default='new', max_length=50, verbose_name='Статус')),
                ('created_note', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_of_completion', models.DateField(auto_now=True, verbose_name='Дата выполнения')),
            ],
            options={
                'verbose_name': 'Список задач',
                'verbose_name_plural': 'Задача',
                'db_table': 'Sketchpad',
            },
        ),
    ]
