# Generated by Django 4.0.5 on 2022-06-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sketchpad',
            options={'verbose_name': 'задача', 'verbose_name_plural': 'Список задач'},
        ),
        migrations.AlterField(
            model_name='sketchpad',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterModelTable(
            name='sketchpad',
            table='sketchpad',
        ),
    ]
