# Generated by Django 4.0.5 on 2022-06-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_sketchpad_options_alter_sketchpad_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sketchpad',
            name='date_of_completion',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
    ]
