# Generated by Django 4.0.5 on 2022-06-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_sketchpad_date_of_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sketchpad',
            name='title',
            field=models.CharField(default='No Title', max_length=50, verbose_name='Заголовок'),
        ),
    ]
